# Generated by Django 5.2.9 on 2026-02-09 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, max_length=80, null=True)),
                ('action', models.CharField(max_length=150)),
                ('target', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='dataapp_aud_created_d1e695_idx'), models.Index(fields=['user'], name='dataapp_aud_user_id_a2a235_idx'), models.Index(fields=['action'], name='dataapp_aud_action_d6125e_idx'), models.Index(fields=['target_type'], name='dataapp_aud_target__78a6cb_idx')],
            },
        ),
    ]
