# Generated by Django 5.2.9 on 2026-02-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='document_types',
            field=models.JSONField(blank=True, default=['invoice', 'purchase order']),
        ),
    ]
