# Generated by Django 5.2.9 on 2026-02-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_alter_environment_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='document_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
