from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.sign_in, name='signin'),
    # path('signup/', views.sign_up, name='signup'),
    path("changepassword/", views.change_password, name="change_password"),
    path('logout/', views.sign_out, name='logout'),
    path("", views.dashboard, name="dashboard"),
    path("environments/<int:env_id>/emails/view/", views.view_environment_emails, name="environment_emails_view"),
    path("environments/<int:env_id>/files/view/", views.view_environment_files, name="environment_files_view"),
    path("environments/create/", views.create_environment, name="environment_create"),
    path("environments/<int:env_id>/edit/", views.edit_environment, name="environment_edit"),
    path("environments/<int:env_id>/delete/", views.delete_environment, name="environment_delete"),
    path("api/scan-inbox/<int:env_id>/", views.scan_inbox, name="api_scan_inbox"),
    path("api/emails/<int:env_id>/", views.list_emails, name="api_list_emails"),
    path("api/emails/<int:email_id>/reprocess/", views.reprocess_email, name="api_reprocess_email"),
    path("api/reprocess-failed/<int:env_id>/", views.reprocess_all_failed, name="api_reprocess_failed"),
    path("api/emails/<int:email_id>/delete/", views.delete_email, name="api_delete_email"),
    path("api/uploads/<int:env_id>/", views.list_uploads, name="api_list_uploads"),
    path("api/uploads/<int:env_id>/upload/", views.upload_files, name="api_new_upload"),
    path("api/uploads/<int:upload_id>/delete/", views.delete_upload, name="api_delete_upload"),
    path("api/uploads/<int:upload_id>/rename/", views.rename_upload, name="api_rename_upload"),
    path("api/uploads/<int:upload_id>/reprocess/", views.reprocess_upload, name="api_reprocess_upload"),
    path("api/uploads/reprocess-failed/<int:env_id>/", views.reprocess_all_failed_uploads, name="api_reprocess_failed_uploads"),
    path("schemas/", views.list_schemas, name="schema_list"),
    path("schemas/create/", views.create_schema, name="schema_create"),
    path("schemas/<int:schema_id>/edit/", views.edit_schema, name="schema_edit"),
    path("schemas/<int:schema_id>/delete/", views.delete_schema, name="schema_delete"),
    path("environments/envmail/<int:email_id>/data/review/", views.review_email_result, name="email_result_review"),
    path("environments/envupload/<int:upload_id>/data/review/", views.review_upload_result, name="upload_result_review"),
    path("environments/envupload/<int:upload_id>/data/save/", views.save_upload_result, name="upload_result_save"),
    path("environments/envmail/<int:email_id>/data/save/", views.save_email_result, name="email_result_save"),
    path("environments/envupload/<int:upload_id>/data/delete/", views.delete_upload_result, name="upload_result_delete"),
    path("environments/envmail/<int:email_id>/data/delete/", views.delete_email_result, name="email_result_delete"),
    path("environments/<int:env_id>/data/view/", views.view_extracted_data, name="view_result_data"),
    path("environments/<int:env_id>/data/get/", views.get_extracted_data, name="get_result_data"),
    path("environments/<int:env_id>/data/export/", views.export_extracted_data, name="export_result_data"),
    path("environments/<int:env_id>/row-source-options/", views.get_extracted_data_row_sources, name="row_source_options"),
    path("account/", views.profile, name="profile"),
     path("api/users/list/", views.list_users, name="api_list_users"),
    path("api/users/add/", views.add_user, name="api_add_user"),
    # path("api/users/<int:user_id>/delete/", views.delete_user, name="api_delete_user"),
    path("api/users/<int:user_id>/edit/", views.edit_user, name="api_edit_user"),
    path("api/audit-logs/", views.audit_logs_api, name="api_audit_logs"),
    path("audit-logs/export/", views.export_audit_logs_csv, name="audit_export_csv"),
    path("audit-logs/", views.view_audit_logs, name="view_audit_logs")
]
